### ISSUE TITLE
can you describe your code 

### ISSUE THREAD

**Issue by StudentWorker** [SXU-CICI/bilstm_mpoa#2]
What class library do you refer to
Where did the dataset you used come from
or more

**Comment by JiyaoWei** [comment]
You can find it in "4.1. Datasets and evaluation index" of the origin paper.

**Comment by StudentWorker** [comment]
我在跑这个代码，我就想问问，我到底要咋改，才能让数据匹配上，代码执行起来。数据集已经下载。

是否我需要修改某些部分，以达到执行起来的目的。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiyaoWei/bilstm_mpoa"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月3日(星期三) 下午3:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JiyaoWei/bilstm_mpoa] can you describe your code  (Issue #2)





 
You can find it in "4.1. Datasets and evaluation index" of the origin paper.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by StudentWorker** [comment]
我在跑这个代码，我就想问问，我到底要咋改，才能让数据匹配上，代码执行起来。数据集已经下载。

是否我需要修改某些部分，以达到执行起来的目的。
类似于我需要&nbsp; &nbsp; python x.py ***后面都跟啥&nbsp; &nbsp; &nbsp;，数据集的目录层次和引用层次。麻烦了，谢谢。


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "JiyaoWei/bilstm_mpoa"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月3日(星期三) 下午3:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JiyaoWei/bilstm_mpoa] can you describe your code  (Issue #2)





 
You can find it in "4.1. Datasets and evaluation index" of the origin paper.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JiyaoWei** [comment]
Firstly, you need to generate a data dictionary, emotion vectors, and modify the directory of the read data. If you want to train with elmo, you need to train it, just as mentioned in the article. Secondly, because the data is managed by the competitor, you may need to simply modify the format of the read data, which should be very basicly.

The catalog hierarchy and reference hierarchy of dataset are not fixed. Just link it to the real catalog. If you have any question about input parameters, you can list it here.

**Comment by StudentWorker** [comment]
Can you apply for a fool teaching like this.&nbsp;
for this code be&nbsp;use by me.
Can I execute code just by looking at GitHub.

very think.
i think more people will need this.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiyaoWei/bilstm_mpoa"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月3日(星期三) 晚上6:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JiyaoWei/bilstm_mpoa] can you describe your code  (Issue #2)





 
Firstly, you need to generate a data dictionary, emotion vectors, and modify the directory of the read data. If you want to train with elmo, you need to train it, just as mentioned in the article. Secondly, because the data is managed by the competitor, you may need to simply modify the format of the read data, which should be very basicly.
 
The catalog hierarchy and reference hierarchy of dataset are not fixed. Just link it to the real catalog. If you have any question about input parameters, you can list it here.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by StudentWorker** [comment]
What data set is the part of the red line




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "JiyaoWei/bilstm_mpoa"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月3日(星期三) 晚上6:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JiyaoWei/bilstm_mpoa] can you describe your code  (Issue #2)





 
Firstly, you need to generate a data dictionary, emotion vectors, and modify the directory of the read data. If you want to train with elmo, you need to train it, just as mentioned in the article. Secondly, because the data is managed by the competitor, you may need to simply modify the format of the read data, which should be very basicly.
 
The catalog hierarchy and reference hierarchy of dataset are not fixed. Just link it to the real catalog. If you have any question about input parameters, you can list it here.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JiyaoWei** [comment]
Because of the copyright problem of the data, we can't put it in the project directly. Next week I will add more detailed data descriptions in GitHub. Of course, these data descriptions can be found in the article already.

**Comment by StudentWorker** [comment]
think very much


 
---Original---
From: ***@***.***&gt;
Date: 2021/11/4 01:07:24
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [JiyaoWei/bilstm_mpoa] can you describe your code  (Issue #2)




 
Because of the copyright problem of the data, we can't put it in the project directly. Next week I will add more detailed data descriptions in GitHub. Of course, these data descriptions can be found in the article already.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by StudentWorker** [comment]
thank you very much.I take a mistake.
what is the vocab_path.I download SMP，Tencent_AILab_Chinese，did i need more dataset?
vocab_path




 
---Original---
From: ***@***.***&gt;
Date: 2021/11/4 01:07:24
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [JiyaoWei/bilstm_mpoa] can you describe your code  (Issue #2)




 
Because of the copyright problem of the data, we can't put it in the project directly. Next week I will add more detailed data descriptions in GitHub. Of course, these data descriptions can be found in the article already.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JiyaoWei** [comment]
The vocab_path is the path of train data dictionary that generated by yourself. You still need the sentiment dictionary of Dalian University of Technology. As mentioned in "4.2. Implementation details" of the origin paper.

**Comment by StudentWorker** [comment]
I see it. I think if you can give me some teaching to creat the vocab like one blog or more is better.this is my first to run a code.so some question like fool.but you are patience.
Thanks again.


 
---Original---
From: ***@***.***&gt;
Date: 2021/11/7 14:37:31
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [JiyaoWei/bilstm_mpoa] can you describe your code  (Issue #2)




 
The vocab_path is the path of train data dictionary that generated by yourself. You still need the sentiment dictionary of Dalian University of Technology. As mentioned in "4.2. Implementation details" of the origin paper.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JiyaoWei** [comment]
Maybe you need to run some basic code, such as rnn, lstm. These works are more suitable as a starting project.

**Comment by JiyaoWei** [comment]
You really love to learn. Best wish to you :)

**Comment by StudentWorker** [comment]
OK.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月7日(星期天) 晚上9:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JiyaoWei/bilstm_mpoa] can you describe your code  (Issue #2)





 
Maybe you need to run some basic code, such as rnn, lstm. These works are more suitable as a starting project.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
